blog/urls.py
from django.conf.urls import url, patterns, include

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^blog/(?P<id>\d+)/$', views.detail, name='detail'),
            ]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    " Define the blog author "
    name = models.CharField(max_length = 50)
    email = models.EmailField(unique = True)
    bio = models.TextField()

    def __str__(self):
        return self.name

class Category(models.Model):
    cat_name = models.CharField('category name', max_length = 50)
    cat_description = models.CharField('category description', max_length = 255)

    def __str__(self):
        return self.cat_name

    class Meta:
        verbose_name_plural = 'Categories'

class Tag(models.Model):
    tag_name = models.CharField(max_length = 50)
    tag_description = models.CharField(max_length = 255)

    def __str__(self):
        return self.tag_name

class Post(models.Model):
    " Define blog post table "
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_date = models.DateTimeField(auto_now_add=False, auto_now=True)
    author = models.ForeignKey(Author)
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post

# Create your views here.
def index(request):
    post = Post.objects.order_by('-created_date')
    # data =  { 'mydata' : 'I miei dati'}
    return render(request, 'blog/index.html', { 'posts' : post})

def detail(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'blog/detail.html', { 'post' : post} )

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="post">
    <h3>Author: {{ post.author}} <br>
    Title: {{post.title}} <br>
    Date: {{post.created_date}} <p>
    <p>Message: <br>{{post.body | linebreaks}}</p></h3>
</div>
<a href="{% url 'blog:index' %}"> Come back to Index</a>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %} All posts {% endblock title %}
{% block content%}
<h1> All posts </h1><br>
{% for post in posts %}
    <div class = "post">
        <h3>Title: {{ post.title }} </h3><br>
        Author: {{ post.author }}<br>
        Created on: {{ post.created_date }}<br>
        <a href="{% url 'blog:detail' id=post.id%}"> Read post </a><p>
    </div>
{% endfor %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>
    </head>
<body>
    <div class="page-header">
        <h1><a href="/">Django Newbie blog</a></h1>
    </div>

    <div class="content">
        <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
         </div>
         </div>
    </div>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </body>
</html>